#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

#echo "bashrc says hello world!"

source ~/.env

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
