#!/bin/sh

# The on-modify event is triggered separately for each task modified. This hook
# script can accept/reject the modification. Processing will continue.

# Input:
# - line of JSON for the original task
# - line of JSON for the modified task, the diff being the modification
read original_task
read modified_task

export root_dir=$(dirname $0)

# processing, should output a modified json and status.
python3 $root_dir/on-modify-calculated-fields.py "$modified_task"
export script_res=$?

# Output:
# - JSON, modified or unmodified.
# - Optional feedback/error.
# echo $modified_task

# Status:
# - 0:     JSON accepted, non-JSON is feedback.
# - non-0: JSON ignored, non-JSON is error.
exit $script_res
